// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://garewxrihhyazifyqaql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcmV3eHJpaGh5YXppZnlxYXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjE0OTcsImV4cCI6MjA1OTY5NzQ5N30.lEBu5x0z2NwPz8ZlAJAC1Bb_I_p5wEmDtKkTYoJhwyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);